import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import QuizTypes from "../components/quiztypes";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
  <div className="flex h-screen">
  <div className="fixed h-screen overflow-y-auto bg-gray-800 text-white w-64">
  <QuizTypes/>
  </div>

  <div className="flex-grow bg-gray-100 p-4">
  {children}
  </div>
</div>
</body>
</html>
  );
}
